#!/usr/bin/python3
print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>Hello Word - First CGI Program</title>')
print('<style> h2 {text-align: center; font-size: 70px;} </style>')
print('<style> .center {display: block; margin-left: auto; margin-right: auto;')
print('width: 50%;} </style>')
print ('</head>')
print ('<body>')
# print ('<h2>Hello Word! This is my first CGI program</h2>')
print ('<h2> Why you click ?? </h2>')
print('<img src="https://www.petwithit.com/wp-content/uploads/2024/02/image-1.jpeg" class="center" alt="picture" >')
print ('</body>')
print ('</html>')
